###

GET http://localhost:3000/api/productos

###
POST http://localhost:3000/api/productos
Content-Type: application/json

{
    "nombre": "Tomate",
    "stock": 69
}

###

GET http://localhost:3000/api/productos/4

###

POST http://localhost:3000/api/productos HTTP/1.1
Content-Type: application/json

{ 
    "nombre": "Berenjena", 
    "stock": 19 
}

###

PUT http://localhost:3000/api/productos/7 HTTP/1.1
Content-Type: application/json

{ 
    "nombre": "Literalmente el bicho", 
    "stock": 99 
}

###
DELETE http://localhost:3000/api/productos/4